### ISSUE TITLE
Put Source folder in htdocs of Xampp Not working

### ISSUE THREAD

**Issue by varundeva** [tbaltrushaitis/cv#1]
It Displays Preload icon only. not loading other.
Whats The Problem?

**Comment by tbaltrushaitis** [comment]
Hi there!

If you just copied src folder - its not enough for things to work. Please run make command as described in README.md [Usage](https://github.com/tbaltrushaitis/cv#runner-usage) section.

Thank you!

**Comment by tbaltrushaitis** [comment]
Hi @varundeva!

Do you need any assistance on how to setup and build?
If yes then do not hesitate to contact me.

Regards!

**Comment by tbaltrushaitis** [comment]
Hi!

So on what step from [Usage section](https://github.com/tbaltrushaitis/cv#runner-usage) and what kind of a problem do you have?

With regards,
-T

**Comment by varundeva** [comment]
Sir
Tell me every procedure
I have just Ubuntu OS .
I never used GIT before

-Varun Deva

**Comment by tbaltrushaitis** [comment]
So that is not about project's code issue.
Closing.

**Comment by hedi777** [comment]
Hello, 

i just tried to use your web template, but i do get the same loader only error when launching the index.html. I just realized i needed to install bower and gulp to make this work which i did. And now i get this error when running make build >>> see image, so it seems there is an issue with the loader not displaying the website. I'm not good enough in coding to give further help, but if you can fix this when you have time would be great, really wanted to tweak around your template. thank you for you time. have a nice day.
![capture d ecran 2019-02-18 a 14 45 07](https://user-images.githubusercontent.com/30708168/52955074-0d1db700-338c-11e9-924f-433661754435.png)

**Comment by tbaltrushaitis** [comment]
Hi @hedi777 !

Thanks for you question! That is very good idea to attach the screenshot with error you caught :+1:
It looks like you didn't install node.js dependencies needed by gulp.
Try to execute 
```shell
$ make setup
```
Or (in case you don't have **make** utility installed in your OS) run
```shell
$ npm i
$ bower i --production
```
in the project's directory.

Once installation process finished you would be able to continue with build.
Hope this helps.

Regards!
