### ISSUE TITLE
Demo Site - Restricted Area - Authorized Users Only

### ISSUE THREAD

**Issue by Neurognostic** [tbaltrushaitis/cv#14]
The link to the demo site requires authentication.

1. Click "Modern CV" link in [README.md](https://github.com/tbaltrushaitis/cv/blob/master/README.md)
2. Shortlink [http://bit.ly/tomascv](http://bit.ly/tomascv) resolves to [https://cv.gsm-center.com.ua/](https://cv.gsm-center.com.ua/)
3. Authentication is requested

> <https://cv.gsm-center.com.ua> is requesting your username and password. The site says: “Restricted Area - Authorized Users Only”

![2019-12-24 17_52_19-Authentication Required-tomascv](https://user-images.githubusercontent.com/23530447/71426860-53136d80-2676-11ea-840d-e76d960d2a15.png)

Request headers:
```
GET / HTTP/1.1
Host: cv.gsm-center.com.ua
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Upgrade-Insecure-Requests: 1
Referer: https://github.com/tbaltrushaitis/cv/blob/master/README.md
Connection: keep-alive
```

Server response headers:
```
HTTP/1.1 401 Authorization Required
Date: Tue, 24 Dec 2019 23:57:16 GMT
Server: Apache
WWW-Authenticate: Basic realm="Restricted Area - Authorized Users Only"
Content-Length: 401
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

**Comment by tbaltrushaitis** [comment]
@Neurognostic, thanks for posting such a detailed issue!

But it looks like you have some misconfiguration or local issue. http://bit.ly/tomascv resolves to HTTP and NOT httpS protocol. And http://cv.gsm-center.com.ua doesn't ask for authorization in my case.
Please check.

Thank you!

**Comment by Neurognostic** [comment]
@tbaltrushaitis, looks like with ["HTTPS Everywhere"](https://www.eff.org/https-everywhere) disabled I can connect.

It was forcefully redirecting my request to use https. Usually it just warns me that https is not available and can proceed with http, but it looks like in this case the server responds on 443 but requires authentication on that port.

**Comment by tbaltrushaitis** [comment]
@Neurognostic, yeah - you are totally right :) 
Should I resolve issue as won't fix issue or you need more help with this?
Thank you!
