### ISSUE TITLE
Demo Site - Down

### ISSUE THREAD

**Issue by Wayne-Jones** [tbaltrushaitis/cv#15]
It seems like when I try to access the Demo Site: http://cv.gsm-center.com.ua/ I'm unable to reach the website. It takes too long to respond and then timed out.

**Comment by tbaltrushaitis** [comment]
@Wayne-Jones ,

yes, this is confirmed. The host is down at all. Will "fix" this in a day or two.

Thank you!

**Comment by tbaltrushaitis** [comment]
@Wayne-Jones ,

VPS troubles resolved. Host is up and live demo working as expected.
Please review and resolve this issue.

Thank you!

**Comment by Wayne-Jones** [comment]
Reviewed and the live demo website is working. Thanks!
