### ISSUE TITLE
Too many animations

### ISSUE THREAD

**Issue by gariasf** [tbaltrushaitis/cv#2]
Perhaps it's just me, but I feel like 40% of the animations are more of a nuisance than an improvement.

Opinions?

**Comment by tbaltrushaitis** [comment]
Hi, @gariasf ,

your question is good and actual, I've just marked it as wont-fix because its not an issue but its not mean that you have to close it - I'm opened to any kind to critic and proposals and need to know how to do this project better is good and every opinion is very important.
