### ISSUE TITLE
Problem with make command

### ISSUE THREAD

**Issue by astabile** [tbaltrushaitis/cv#24]
Hi! This is the best CV template that I even see!

I have a problem with the make command (I already installed previously the dev tools).

Attached screenshot, wait for your answer.

All the best!

![image](https://user-images.githubusercontent.com/1737391/85740638-2a793880-b6d8-11ea-8480-d22aef60c6fd.png)

**Comment by astabile** [comment]
BTW: I'm on win10 but already installed the previous tools for npm:
`npm install --global --production windows-build-tools`

**Comment by tbaltrushaitis** [comment]
Hi, @astabile !

Can you please attach npm-debug.log ?

Thank you!

**Comment by astabile** [comment]
Already solved bro. You can close it.

Thanks!

**Comment by tbaltrushaitis** [comment]
@astabile , wow!

Silence is gold (с)
;-)

Thank you!
