### ISSUE TITLE
issue can't deploy this project

### ISSUE THREAD

**Issue by aryan22796** [tbaltrushaitis/cv#26]
sir , 
what are the step run this project and edit

**Comment by tbaltrushaitis** [comment]
Hi @aryan22796 !

Was you able to read `usage` section of README.md file?

If you have any errors, please provide log file.

Thank you!

**Comment by Mraghuvaran** [comment]
This will create/update webroot directory inside the project root. Use this directory as DocumentRoot in VirtualHost configuration of your web server. 

I'm done with the 5 steps given . Could you please help me with how to process the above step. I'm not a computer science guy. I have very experience in coding.

**Comment by tbaltrushaitis** [comment]
> This will create/update webroot directory inside the project root. Use this directory as DocumentRoot in VirtualHost configuration of your web server.
> 
> I'm done with the 5 steps given . Could you please help me with how to process the above step. I'm not a computer science guy. I have very experience in coding.

@Mraghuvaran , configuring of web-server is out of scope of this repository. Its just a website engine/template and configuration of web-server that will serve requests to it - its only up to you.

Please let me know if you have any issues with source code.
Thank you!

**Comment by Mraghuvaran** [comment]
I understand, Could you help in doing that on top of that.


*Thanks & Regards*
*Raghuvaran.*

**Comment by tbaltrushaitis** [comment]
> I understand, Could you help in doing that on top of that. *Thanks & Regards* *Raghuvaran.*

Can't estimate and measure possibilities with no data input. Please clarify.

Thank you!

**Comment by Mraghuvaran** [comment]
Hey Tbaltrushaitis, I have the data filled in as per the instructions , now
I can share that folder will you be able to run it on a server ?

*Thanks & Regards*
*Raghuvaran.*

**Comment by tbaltrushaitis** [comment]
> Hey Tbaltrushaitis, I have the data filled in as per the instructions , now I can share that folder will you be able to run it on a server ? *Thanks & Regards* *Raghuvaran.*

Hi!
Unfortunately, my host already handles demo for this repo.
You should get your own and deploy builded sources :+1: 

With kind regards,
-Tom

**Comment by tbaltrushaitis** [comment]
Closing
