### ISSUE TITLE
environment in window 10

### ISSUE THREAD

**Issue by vijaypatidar1** [tbaltrushaitis/cv#29]
![Screenshot (4)](https://user-images.githubusercontent.com/76774880/103349439-d144f400-4ac2-11eb-9f0a-d929c946bac0.png)
module not found

**Comment by tbaltrushaitis** [comment]
Hi, @vijaypatidar1!

I'm a little bit confused with your post and can't understand, how it relates to CV repository?
Can you please explain?

Thank you!

**Comment by vijaypatidar1** [comment]
there are 4 error that is module not found.

**Comment by tbaltrushaitis** [comment]
> there are 4 error that is module not found.

Sorry, but this is not informative. I can't be sure even that you read the manual about how to use this project because there is no such command in it:

```bash
$ node --trace-warnings
```

Regards!

**Comment by vijaypatidar1** [comment]
![image](https://user-images.githubusercontent.com/76774880/104154006-c61a8e00-5409-11eb-9fe5-260aaa210a1a.png)

this error occur after make setup

**Comment by tbaltrushaitis** [comment]
Hi, @vijaypatidar1!

There is obviously that you don't have a `make` binary. Please setup it.

Regards!

**Comment by tbaltrushaitis** [comment]
Closing due to reporter inactivity.
