### ISSUE TITLE
No rule to make target setup. Stop.

### ISSUE THREAD

**Issue by Enzo-ltz** [tbaltrushaitis/cv#30]
Hello Sir ! 

I would like to run your project locally, but I'm not able to "make setup" as required. Here's the error I've got. I already installed "make" with chocolatey, under windows 10.

Hope you can help me !

![image](https://user-images.githubusercontent.com/71329859/108131151-28257d80-70b1-11eb-915e-5db993f4c517.png)

**Comment by tbaltrushaitis** [comment]
Hi!

Try to delete file `/e/COURS/DIM/Anglais/english-portfolio/build-0.3.0` before run `make setup`.
Also I would recommend to switch to **dev** branch - it currently have a little bit more functionality and less bugs.

Hope this helps!

**Comment by Enzo-ltz** [comment]
I tried switching branch and delete build file, but it's still not working :( Same error

**Comment by tbaltrushaitis** [comment]
Hi!

Thank you for your comment with additional details!
Try to run `make clean` before any other actions?

Thank you!

**Comment by tbaltrushaitis** [comment]
@Enzo-ltz ,

any updates on this?

Thank you!

**Comment by Enzo-ltz** [comment]
Hi ! Sorry for not answering last time.
I couldn't make it run even with make clean so I had to move on something else, I'm not gonna have  time to work on this for a while, maybe later.
If you want to close the issue maybe you can do it since I won't be able to figure out what's going wrong on my computer.

Thank's for helping me !

**Comment by tbaltrushaitis** [comment]
@Enzo-ltz ,

You're welcome!

Closing.
