### ISSUE TITLE
ReferenceError thrown during deployment

### ISSUE THREAD

**Issue by jhademcconnell** [tbaltrushaitis/cv#33]
Ran the setup steps as outlined but when trying to deploy, the following error is thrown:

fs.js:27
const { Math, Object } = primordials;
                         ^
ReferenceError: primordials is not defined
    at fs.js:27:26

    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
=============================================================
Error message: > cv@0.2.6 preinstall /workspace
> set echo off; figlet-toilet -t -f small -F border 'NPM:PRE-INSTALL'

sh: 1: figlet-toilet: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! cv@0.2.6 preinstall: `set echo off; figlet-toilet -t -f small -F border 'NPM:PRE-INSTALL'`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the cv@0.2.6 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tbaltrushaitis** [comment]
Hi, @jhademcconnell.

Looks like you need to install `figlet-toilet` package in your system first. Do it with your system installer. 
For example in **ubuntu** OS the command will look like:

`$ sudo apt install figlet-toilet`

Regards!

**Comment by tbaltrushaitis** [comment]
@jhademcconnell ,

do you need assistance on this or it may be closed?

Thanks in advance!

**Comment by tbaltrushaitis** [comment]
Closing due to reporter inactivity

**Comment by SamGreenwood1** [comment]
I'm having a similar issue but have figlet-toilet installed.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/20076209/197633023-39272282-abe6-42ae-93a0-809b76b38c63.png">

<img width="438" alt="image" src="https://user-images.githubusercontent.com/20076209/197633135-20a70553-9ff1-4cd4-8ac1-542dbba62e5b.png">

**Comment by tbaltrushaitis** [comment]
@SamGreenwood1 ,

run `npm i dotenv`

Regards!
