### ISSUE TITLE
Update Readme File

### ISSUE THREAD

**Issue by Shaishav0507** [tbaltrushaitis/cv#37]
Hey @tbaltrushaitis 
I would like to add contribution guidelines, code of conduct, project admin and license in readme file.
Please assign it to me.
Thanks

**Comment by tbaltrushaitis** [comment]
Hi, @Shaishav0507!

All of those files are included in repository and linked in [README.md](https://github.com/tbaltrushaitis/cv/blob/master/README.md) file.
Can you find them exists?

Thank you!

**Comment by Shaishav0507** [comment]
Hi, @tbaltrushaitis 
I could only see the license linked in the readme file.
Others I can't find them.

**Comment by Shaishav0507** [comment]
@tbaltrushaitis 
Can I work on this issue ?
