### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hareeshdwivedi** [tbaltrushaitis/cv#49]
> figlet-toilet -t -f small -F border 'NPM: START'

'figlet-toilet' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cv@0.3.0 start: `figlet-toilet -t -f small -F border 'NPM: START'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cv@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

This is coming now will you please tell me the commands to run these as what you have said in your Readme i had done all those but reached to no conclusion

**Comment by tbaltrushaitis** [comment]
Hi!

This package should be installed (as others needed) when you run [make install](https://github.com/tbaltrushaitis/cv#two-install-dependencies)

Hope this helps!
