### ISSUE TITLE
Installation Still Not Working: Make Processes Ran Successfully But Webpage 403s

### ISSUE THREAD

**Issue by SamGreenwood1** [tbaltrushaitis/cv#55]
@tbaltrushaitis I noticed that there's a reference to `/var/www/html/cv.git/webroot` in `~/cv/etc/nginx/sites-available/010-cv` but, that file doesn't exist on my server. Is `cv.git` supposed to be a link to the cv directory?

2:37 PM ET: just tried that it didn't help. I realized that there's an ssl error when I try to access it over HTTPS. are your certs in the repo?

_Originally posted by @SamGreenwood1 in https://github.com/tbaltrushaitis/cv/issues/52#issuecomment-1302471913_

**Comment by tbaltrushaitis** [comment]
> @tbaltrushaitis I noticed that there's a reference to `/var/www/html/cv.git/webroot` in `~/cv/etc/nginx/sites-available/010-cv` but, that file doesn't exist on my server. Is `cv.git` supposed to be a link to the cv directory?

> 2:37 PM ET: just tried that it didn't help. I realized that there's an ssl error when I try to access it over HTTPS. are your certs in the repo?
> 

Answered [here](https://github.com/tbaltrushaitis/cv/issues/52#issuecomment-1303256549)

**Comment by SamGreenwood1** [comment]
I ended up restarting the setup process and am getting this error I don't remember how I fixed it.

**Comment by SamGreenwood1** [comment]
I ended up restarting the setup process and am getting this error I don't remember how I fixed it.
![image](https://user-images.githubusercontent.com/20076209/200139262-2c85f170-59e0-44a0-a328-f27c3d642fd0.png)

**Comment by tbaltrushaitis** [comment]
> I ended up restarting the setup process and am getting this error I don't remember how I fixed it. ![image](https://user-images.githubusercontent.com/20076209/200139262-2c85f170-59e0-44a0-a328-f27c3d642fd0.png)

Its not the CV repo problem. Looks like some kind of network issue or so...

**Comment by SamGreenwood1** [comment]
Now getting a different error: 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/20076209/201237844-7583813f-ff3e-45b6-8017-13c65e98874a.png">
