### ISSUE TITLE
"make build" -- Need Help

### ISSUE THREAD

**Issue by md-rubel** [tbaltrushaitis/cv#6]
I have successfully ran `make setup` command. but while running `make build` command getting the following error, (please see screen-shots):

(Please note that i am from ubuntu 18.04.2)

![](https://extraimage.net/images/2019/07/11/76b75d8e2eb4155871f6d60799145ced.png)

![](https://extraimage.net/images/2019/07/11/b7b7e9af1114a0e07268cf6c13e1d680.png)

**Comment by tbaltrushaitis** [comment]
Hi, @md-rubel !
Thank you for your detailed issue report! It looks very strange but seems that bower components installation wasn't started during 'make setup'. Try to run `bower i` and then continue with 'make build'.
Please let me know if that help or issue still exists.

Thank you!

**Comment by md-rubel** [comment]
Thanks a lot,  that worked !

**Comment by md-rubel** [comment]
Hello brother, i need another help. It will be really help for me if you let me know where to change code if want to deploy it to Netlify. Actually i tried and got errors. Here is my logs:

![](https://extraimage.net/images/2019/07/12/d2e074bd75e4b7d4c5a5150d8c6f2d0e.png)
![](https://extraimage.net/images/2019/07/12/d299b139335dffe04d64a8a668cdce75.png)
![](https://extraimage.net/images/2019/07/12/045e38c023c02ababae99620bcb91afb.png)
![](https://extraimage.net/images/2019/07/12/b887b8bd1802c575edf7467ad07ff7db.png)
![](https://extraimage.net/images/2019/07/12/50dfcc6c92d703d524e989175a9766ff.png)

I'm looking for your response eagerly.

**Comment by tbaltrushaitis** [comment]
Hi, @md-rubel!

I've look at the each screenshot you sent and found only several warnings but its not some kind of critical errors that can block deployment process.
Also I'm not familiar with Netlify. But I'm sure that you should try to deploy again and maybe next time it will be successful? :cat2:

**Comment by md-rubel** [comment]
Thanks for your reply.

**Comment by md-rubel** [comment]
One more query, please let me know where have you hosted this website/repository ?  I will be really thankful.

**Comment by tbaltrushaitis** [comment]
> One more query, please let me know where have you hosted this website/repository ? I will be really thankful.

It is hosted on my private virtual server (VPS) under apache web server.
Hope this helps :-)

Thank you!
